EM-27 Allow Synchronous events
Cecropia/Event-Manager pull request #30
Opened 2020-11-13 20:59 UTC by ssanabriacec

Resolves #27 

Restrict to only one Synchronous Register

Call Synchronous only if Payload has the boolean

- Synchronous also comes from the incomming payload.

Restoring to execute all async first then sync

- We execute first all the Async calls
- We execute last the Sync call to not interrupt the Async calls
- We return the Sync response payload to the EM endpoint back to the caller

Callback return response

2020-11-16 18:03 UTC, tupini07 requested changes

2020-11-16 18:03 UTC, tupini07 commented on BusinessLogic/Entities/EventDispatcher.cs
> +
Let's add some documentation here to ensure that it is clear what is happening

```suggestion
            // If there is already a synchronous subscription then raise an exception
```

2020-11-16 18:03 UTC, tupini07 commented on BusinessLogic/Entities/EventDispatcher.cs
> +                    if (!subscription.Synchronous)
The `if` check above is not necessary because we're already **only** iterating through the subscriptions where `!x.Syncrhonous`

2020-11-16 18:03 UTC, tupini07 commented on BusinessLogic/Entities/EventDispatcher.cs
> +
Add a comment:

```suggestion
                // if there is no synchronous event then just return an empty response with 200 status code
```

2020-11-16 18:03 UTC, tupini07 commented on EventManager.csproj
> +    <Version>2.0</Version>
Please add a patch version so that we respect semantic versioning:

```suggestion
    <Version>2.0.0</Version>
```

2020-11-16 18:03 UTC, tupini07 commented on BusinessLogic/Entities/Subscription.cs
> +                        if (this.Synchronous)
Add a comment above:

```suggestion
                        // if the subscription is synchronous then it should only have one callback so we're safe returning its response here
                        if (this.Synchronous)
```

2020-11-16 18:03 UTC, tupini07 commented on Middleware/EventManagerMiddleware.cs
> +                if (httpResponseMessage == null)
Add comment

```suggestion
                // if the response message is `null` then it means the event had no synchronous callbacks and that all
                // async callbacks have been queued for execution, see we can return 200 status
                if (httpResponseMessage == null)
```

2020-11-16 20:08 UTC, ssanabriacec commented on BusinessLogic/Entities/EventDispatcher.cs
> +                    if (!subscription.Synchronous)
fixed

2020-11-16 20:09 UTC, ssanabriacec commented on EventManager.csproj
> +    <Version>2.0</Version>
fixed too

2020-11-16 20:09 UTC, ssanabriacec commented on Middleware/EventManagerMiddleware.cs
> +                if (httpResponseMessage == null)
fixed too

2020-11-16 20:09 UTC, ssanabriacec commented on BusinessLogic/Entities/Subscription.cs
> +                        if (this.Synchronous)
fixed too

2020-11-16 20:09 UTC, ssanabriacec commented on BusinessLogic/Entities/EventDispatcher.cs
> +
fixed too

2020-11-16 20:09 UTC, ssanabriacec commented on BusinessLogic/Entities/EventDispatcher.cs
> +
fixed too

2020-11-17 13:39 UTC, tupini07 approved these changes

2020-11-17 14:00 UTC, merged